version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: thymian-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "${DB_EXTERNAL_PORT_DB}:${DB_INTERNAL_PORT_DB}"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "mysqladmin" , "ping", "-h", "localhost", "-p${MYSQL_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s

  app:
    image: thymian-app:latest
    container_name: thymian-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "${APP_EXTERNAL_PORT}:${APP_INTERNAL_PORT}"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    restart: always

volumes:
  mysql_data:
