spring:
  application:
    name: thymian

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jackson:
  default-property-inclusion: non_null

server:
  port: 8080
