name: Thymian 자동 배포 → Mac mini

# main 브랜치에 push될 때마다 실행
on:
  push:
    branches:
      - main

jobs:
  deploy-to-macmini:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) SSH로 맥미니에 접속하여 deploy 스크립트 실행
      - name: Deploy to Mac mini
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.MAC_HOST }}
          username: ${{ secrets.MAC_USER }}
          key: ${{ secrets.MAC_SSH_KEY }}
          port: 2200
          script: |
            # (A) 배포 스크립트 위치로 이동
            cd ~/scripts

            # (B) 실제 배포 실행
            ./deploy_thymian.sh
