name: Thymian CI/CD → Mac mini

# main 브랜치에 push가 발생할 때마다 워크플로우가 실행
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean bootJar -x test

      # 4. SSH 접속 후 배포 스크립트 실행
      - name: Deploy to Mac mini via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.MAC_HOST }}
          username: ${{ secrets.MAC_USER }}
          key: ${{ secrets.MAC_SSH_KEY }}
          port: 22
          script: |
            set -e

            # (A) 배포 디렉터리로 이동 
            cd ~/projects/thymian-backend

            # (B) Git 저장소가 없으면 clone, 있으면 최신 코드로 리셋
            if [ ! -d .git ]; then
              git clone https://github.com/austinhong22/Thymian_back.git .
            else
              git fetch --all
              git reset --hard origin/main
            fi

            # (C) 의존성 다운로드 & 빌드
            ./gradlew clean bootJar -x test

            # (D) 이전에 실행 중인 프로세스(포트 8080) 종료
            PID=$(lsof -ti tcp:8080)
            if [ -n "$PID" ]; then
              kill -9 $PID || true
            fi

            # (E) 새로 빌드된 JAR을 백그라운드로 실행
            nohup java -jar build/libs/*SNAPSHOT.jar \
              --spring.profiles.active=prod \
              > ~/logs/thymian.log 2>&1 &

            # (F) 성공 메시지 출력 (옵션)
            echo "✔️ Thymian has been deployed on Mac mini."
